baseURL = 'https://example.com/'
languageCode = 'en-us'
title = 'My Blog - Gradient Flow Theme'
theme = '../..'

[params]
    # Site Configuration
    author.name = "John Doe"
    author.bio = "Developer and technical writer"
    
    # Social Media
    github = "username"
    linkedin = "username"
    
    # Analytics
    googleAnalytics = "GA-TRACKING-ID"
    disqusShortname = "site-shortname"
    
    # Favicon
    favicon = "/favicon.ico"
    
    # Navigation Configuration
    # Pages in content/menu/ will automatically appear in navigation dropdown

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 10

  [[menu.main]]
    name = 'Blog'
    url = '/posts'
    weight = 20

  [[menu.main]]
    identifier = 'menu'
    name = 'Pages'
    title = 'Site Pages'
    weight = 30

  [[menu.main]]
    name = 'About'
    parent = 'menu'
    url = '/menu/about'
    weight = 31

  [[menu.main]]
    name = 'Team'
    parent = 'menu'
    url = '/menu/team'
    weight = 32

  [[menu.main]]
    identifier = 'resources'
    name = 'Resources'
    title = 'Help & Documentation'
    weight = 40

  [[menu.main]]
    name = 'Documentation'
    parent = 'resources'
    url = '/docs'
    weight = 41

  [[menu.main]]
    name = 'Support'
    parent = 'resources'
    url = '/support'
    weight = 42

  [[menu.main]]
    name = 'Categories'
    url = '/categories'
    weight = 50

  [[menu.main]]
    name = 'Tags'
    url = '/tags'
    weight = 60

[pagination]
  pagerSize = 3

# Custom CSS/JS
params.customCSS = ["/css/custom.css"]
params.customJS = ["/js/custom.js"]
